### ISSUE TITLE
Create VPC in us-west-2 region.

### ISSUE THREAD

**Issue by sredhar** [ibexlabs/skubana-devops#1]
Please create a VPC with following subnets 

VPC CIDR - 10.0.0.0/16  (3 AZ)

Public Subnets

10.0.0.0/24
10.0.1.0/24
10.0.2.0/24

Private Subnets

10.0.100.0/24
10.0.101.0/24
10.0.102.0/24

With hosted NAT Gateway, New Key and Internet Gateway & Routing Tables.

**Comment by zihaoyu** [comment]
Key is `skubana-devops`

**Comment by zihaoyu** [comment]
https://github.com/Skubana/devops-new/pull/1
